config/routes.rb
Rails.application.routes.draw do




  namespace :public do
    get "orders/complete" => "orders#complete", as: "complete"
    post "orders/confirm" => "orders#confirm", as: "confirm"
    resources :orders, only: [:new, :index, :show, :create]
  end

  namespace :public do
    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  namespace :public do
    resources :items, only: [:index, :show,]
  end
  namespace :public do
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :public do
     get 'customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
     patch 'customers/withdraw' => "customers#withdraw", as: "withdraw"
     resources :customers, only: [:show, :edit, :update]
  end

  namespace :public do
  get "homes/top"
  get "homes/about"
  end

  namespace :admin do
   resources :order_detail, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    get 'homes/top'
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  namespace :admin do
   resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
enum method_of_payment: { credit_card: 0, transfer: 1 }
enum order_status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
 belongs_to :customer
 has_many :order_details
 
attribute :shipping_cost, :integer, default: 800
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, completion: 3 }
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to '/admin/genres'
  end
  
  def destroy
  @genre = Genre.find(params[:id])
  @genre.destroy
  redirect_to admin_genres_path
  end
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page])
    @total = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to '/admin/items'
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end


  
  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
  
  

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end
  
  def update
  @order = Order.find(params[:id])
  @order.update(order_params)
  redirect_to admin_order_path(@order)
  end
  
  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :billing_amount, :method_of_payment, :order_status)
  end
  
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters , if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana, :first_name_kana, :last_name, :first_name, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
      if admin_signed_in?
       admin_homes_top_path
      else customer_signed_in?
       public_homes_top_path
      end
  end

  def after_sign_out_path_for(resource)
      if resource == :admin
          new_admin_session_path
      else
          public_homes_top_path
      end      
  end 
 end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<main>
    <div class="container">
  <div class="row ml-5">
    <div class="col-lg-4 text-center">
  <h4 class="text-black bg-secondary  mt-5 mb-5">ジャンル編集</h4>
  </div>
  </div>

<div class="row">
<div class="col-lg-2"> 
<%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
<label for="genre">ジャンル名</label>
</div> 
<div class="col-lg-3">
<%= f.text_field(:name, placeholder: "キャンディ") %>
</div>
<div class="col">
<%= f.submit '変更を保存', class: "btn btn-success" %>
<% end %>
</div>
</div>
</div>

app/views/admin/genres/index.html.erb
<main>
    <div class="container">
  <div class="row ml-5">
    <div class="col-lg-4 text-center">
  <h4 class="text-black bg-secondary  mt-5 mb-5">ジャンル一覧・追加</h4>
  </div>
  </div>
  
<div class="row">
<div class="col-lg-2">
<%=form_with model: @genre, url: 'genres', method: :post do |f| %>
<label for="genre">ジャンル名</label>
</div>
<div class="col-lg-3">
<%= f.text_field(:name, placeholder: "ジャンル名") %>
</div>
<div class="col">
<%= f.submit '新規登録', class: "btn btn-success" %>
<% end %>
</div>
</div>

<div class="col-lg-5 mt-5">
<table class="table">
  <thead>
    <tr class="table-active">
    <th>ジャンル</th>
    <th></th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%=link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/items/edit.html.erb
<main>
    <div class="container">
  <div class="row ml-2">
    <div class="col-lg-4 text-center">
  <h4 class="text-black bg-secondary  mt-5 mb-5">商品編集</h4>
  </div>
  </div>
  
<div class="container text-center">
<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
<div class= "row justify-content-center mb-4">
    <div class="col-2">
        商品画像
    </div>
    <div class="col-3">
        <%= f.file_field :image, placeholder: "商品画像", accept: "image/*" %>
    </div>
</div>

<div class="row justify-content-center mb-4">
<div class="col-2">
    商品名
</div>
<div class="col-3">
    <%= f.text_field :name %>
</div>
</div>

<div class="row justify-content-center mb-4 ">
    <div class="col-2">
        商品説明
    </div>
    <div class="col-3">
        <%= f.text_area :introduction %>
    </div>
</div>

<div class="row justify-content-center mb-4 ">
    <div class="col-2">
        ジャンル
    </div>
    <div class="col-3">
        <%= f.collection_select :genre_id, @genres, :id, :name,  {prompt: "選択してください"} %>
    </div>
</div>

<div class="row justify-content-center mb-4 ">
    <div class="col-2">
        税抜き価格
    </div>
    <div class="col-3">
        <%= f.text_field :price %>円
    </div>
</div>

<div class="row justify-content-center mb-4 ">
    <div class="col-2">
        販売ステータス
    </div>
    <div class="col-3">
<label><%= f.radio_button :is_active, "true" %>販売中</label>
<label><%= f.radio_button :is_active, "false" %>販売停止中</label>
    </div>
</div>

<div class="row justify-content-center mb-4 ">
    <div class="col">
        <%= f.submit "変更を保存", class: "btn btn-success" %>
    </div>
    <% end %>
</div>
</div>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
<div class="text-center mt-5 col-lg-2">
  <h4 class="text-black bg-secondary ">商品一覧</h4>
</div>
<div class="col mb-3">
<div class=" text-right">
<%= link_to  new_admin_item_path, method: :get, class: "btn btn-light text-secondary fa-15" do %>
<i class="fas fa-plus-circle"></i>
<% end %>
</div>
</div>


<table class="table">
  <thead>
    <tr class="table-active">
      <th>商品ID</th>
      <th>商品名</th>
       <th>税抜価格</th>
        <th>ジャンル</th>
         <th>販売ステータス</th>
    </tr>
    </thead>
<% @items.each do |item| %>
<tbody>
<tr>
  <td>
    <%= item.id %>
    </td>
   <td>
     <u>
     <%= link_to item.name, admin_item_path(item.id), class: "text-dark" %>
     </u>
     </td>
    <td>
      <%= item.price %>
      </td>
     <td>
       <%= item.genre.name %>
       </td>
       <% if item.is_active == true %>
      <td class="text-success font-weight-bold">
        販売中
      </td>
     <% else %>
     <td class="text-secondary">
       販売停止中
     </td>
     <% end %>


        </tr>
        </tbody>
<% end %>
</tr>
</tbody>
</table>
<div class="row justify-content-center">
  <div class="col-3">
<%= paginate @items %>
</div>
</div>
</div>
</main>

app/views/admin/items/new.html.erb
<main>
<div class="container">
  <div class="text-center mt-5 col-lg-2">
    <h4 class="text-black bg-secondary">商品新規登録</h4>
  </div>


<div lcass="form-horizontal" role="form">
<%= form_with model: @item, url: admin_items_path,  method: :post do |f| %>
<div class="form-grop mt-5">
<div class="row justify-content-center">
<div class="col-sm-2">
<label for="image" class="col-form-label">商品画像</label>
</div>
<div class="col-sm-7">
<%= f.file_field :image, accept: 'image/*' %>
</div>
</div>
</div>


<div class="form-grop mt-3">
  <div class="row justify-content-center">
    <div class="col-sm-2">
  <lavel for="name" class="col-form-label">商品名</lavel>
  </div>
  <div class="col-sm-7">
<%= f.text_field(:name, placeholder: "商品名", size: "40") %>
</div>
</div>
</div>

<div class="form-grop mt-3">
  <div class="row justify-content-center">
     <div class="col-sm-2">
     <lavel for="introduction" class="col-form-label">商品説明</lavel>
     </div>
      <div class="col-7">
<%= f.text_area(:introduction, placeholder: "ここに説明文を記述します", size: "40*30" )  %>
</div>
</div>
</div>

<div class="form-grop mt-3">
   <div class="row justify-content-center">
     <div class="col-sm-2">
     <lavel for="renre" class="col-form-label">ジャンル</lavel>
     </div>
      <div class="col-sm-7">
<%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "選択してください"} %>
</div>
</div>
</div>

<div class="form-grop mt-3">
   <div class="row justify-content-center">
     <div class="col-sm-2">
     <lavel for="price" class="col-form-label">税抜価格</lavel>
     </div>
      <div class="col-sm-7">
<%= f.text_field(:price, placeholder: "1000", size: "40") %>円
</div>
</div>
</div>

<div class="form-grop mt-3">
   <div class="row justify-content-center">
     <div class="col-sm-2">
     <lavel for="renre" class="col-form-label">販売ステータス</lavel>
     </div>
     <div class="col-sm-7">
<label><%= f.radio_button :is_active, "true" %>販売中</label>
<label><%= f.radio_button :is_active, "false" %>販売停止中</label>
</div>
</div>
</div>
<div class="row justify-content-center">
<div class="col-4">
  <%= f.submit '新規登録', class: "btn btn-success btn-lg"%>
  </div>
</div>
<% end %>
</div>
</div>
</div>
</div>
</main>

app/views/admin/items/show.html.erb
<main>
    <div class="container">
      
  <div class="row ml-5">
    <div class="col-lg-4 text-center">
  <h4 class="text-black bg-secondary  mt-5 mb-5">商品詳細</h4>
  </div>
  </div>
  
  <div class="row">
  <div class="col-4">
  <%= image_tag @item.image %>
  </div>
  
 <div class="col-7">
  <div class="row mb-4">
   <div class="col-3">
    商品名
   </div>
  <div class="col-9">
   <%= @item.name %>
  </div>
 </div>
 
 <div class="row mb-4">
  <div class="col-3">
   商品説明  
  </div>
  <div class="col-9">
   <%= @item.introduction %>
  </div>
 </div>

 <div class="row mb-4">
  <div class="col-3">
   ジャンル
  </div>
  <div class="col-9">
   <%= @item.genre.name %>
  </div>
 </div>

 <div class="row mb-4">
  <div class="col-3">
   税込価格<br>(税抜価格)
  </div>
  <div class="col-9">
   <%= @item.with_tax_price.to_s(:delimited) %>（<%= @item.price.to_s(:delimited) %>）円
  </div>
 </div>
 
  <div class="row mb-4">
  <div class="col-3">
   販売ステータス
  </div>
  <div class="col-9">
  <% if @item.is_active == true %>
  <div class="col-7 text-success font-weight-bold">
  販売中
  </div>
<% else %>
<div class="col-7 text-secondary">
  販売停止中
  </div>
<% end %>
</div>
  </div>
 </div>
 
<div class="col text-center">
<%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</main>
 

app/views/admin/orders/show.html.erb
<main>
<div class="container">
  <div class="text-center mt-5 col-lg-2">
    <h4 class="text-black bg-secondary">注文履歴詳細</h4>
  </div>

<div class="row mb-2">
  <div class="col-2">
    購入者
  </div>
  <div class="col">
    <u><%= @order.customer.last_name + @order.customer.first_name %></u>
  </div>
</div>

<div class="row mb-2">
  <div class="col-2">
    注文日
  </div>
  <div class="col">
    <%= @order.created_at.strftime('%Y/%m/%d') %>
  </div>
</div>

<div class="row mb-2">
  <div class="col-2">
    配送先
  </div>
  <div class="col">
    <%= @order.postal_code + @order.address %><br>
    <%= @order.name %>
  </div>
</div>

<div class="row mb-2">
  <div class="col-2">
    支払い方法
  </div>
  <div class="col">
    <%= @order.method_of_payment_i18n %>
  </div>
</div>
<%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
<div class="row mb-4 ">
  <div class="col-2">
    注文ステータス
  </div>
  <div class="col-3">
    <%= f.select :order_status, Order.order_statuses_i18n.keys, {}, class: "order_status" %>
  </div>
  <div class="col">
    <%= f.submit "更新", class: "btn btn-success" %>
  </div>
</div>
<% end %>

<div class="container">
<div class="row">
  <div class="col-8">
<table class="table">
  <thead>
    <tr class="table-active">
    <th>商品名</th>
    <th>単価（税込）</th>
    <th>数量</th>
    <th>小計</th>
    <th>製作ステータス</th>
    <th></th>
    </tr>
  </thead>
  <tbody>
    <% @order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td><%= order_detail.price %></td>
      <td><%= order_detail.quantity %></td>
      <td><%= order_detail.price * order_detail.quantity %></td>
     <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
      <td><%= f.select :production_status, OrderDetail.production_statuses_i18n.keys, {}, class: "production_status" %></td>
      <td><%= f.submit "更新", class: "btn btn-success" %></td>
       <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
</div>


<div class="col-4 align-self-end">
  <div class="col-12 mb-2">
    商品合計
    <%= @order.billing_amount %>
    </div>
      <div class="col-12 mb-2">
           送料
          <%= @order.shipping_cost %>
      </div>
      <div class="col-12 mb-2">
          請求金額合計
        <%= @order.billing_amount + @order.shipping_cost %>
      </div>
      </div>
</div>
</div>
</div>