config/routes.rb
Rails.application.routes.draw do




  namespace :public do
    get "orders/complete" => "orders#complete", as: "complete"
    post "orders/confirm" => "orders#confirm", as: "confirm"
    resources :orders, only: [:new, :index, :show, :create]
  end

  namespace :public do
    delete 'cart_items/destroy_all' => "cart_items#destroy_all", as: "destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  namespace :public do
    resources :items, only: [:index, :show,]
  end
  namespace :public do
   resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :public do
     get 'customers/unsubscribe' => "customers#unsubscribe", as: "unsubscribe"
     patch 'customers/withdraw' => "customers#withdraw", as: "withdraw"
     resources :customers, only: [:show, :edit, :update]
  end

  namespace :public do
  get "homes/top"
  get "homes/about"
  end

  namespace :admin do
   resources :order_detail, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    get 'homes/top'
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :create, :new, :show, :edit, :update, :destroy]
  end

  namespace :admin do
   resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_for :admin,  skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }


  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
enum method_of_payment: { credit_card: 0, transfer: 1 }
enum order_status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
 belongs_to :customer
 has_many :order_details
 
attribute :shipping_cost, :integer, default: 800
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum production_status: { cannot_be_manufactured: 0, waiting_for_production: 1, production: 2, completion: 3 }
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to '/admin/genres'
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to '/admin/genres'
  end
  
  def destroy
  @genre = Genre.find(params[:id])
  @genre.destroy
  redirect_to admin_genres_path
  end
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page])
    @total = 0
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to '/admin/items'
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end


  
  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters , if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name_kana, :first_name_kana, :last_name, :first_name, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
      if admin_signed_in?
       admin_homes_top_path
      else customer_signed_in?
       public_homes_top_path
      end
  end

  def after_sign_out_path_for(resource)
      if resource == :admin
          new_admin_session_path
      else
          public_homes_top_path
      end      
  end 
 end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">




              <% if admin_signed_in? %>

                <li class="nav-item">
               <%= link_to "商品一覧", admin_items_path, class: "nav-link text-dark" %>
              </li>
               <li class="nav-item">
               <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-dark" %>
              </li>
               <li class="nav-item">
               <%= link_to "注文履歴一覧", admin_homes_top_path, class: "nav-link text-dark" %>
              </li>
               <li class="nav-item">
               <%= link_to "ジャンル一覧", admin_genres_path, class:"nav-link text-dark" %>
              </li>
                <li class="nav-item">
               <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,  class:"nav-link text-dark" %>
              </li>

             <% elsif customer_signed_in? %>

                 <li class="nav-item">
                <%= link_to "マイページ", public_customer_path(current_customer), class: "nav-link text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to "商品一覧", public_items_path, class: "nav-link text-dark" %>
              </li>
               <li class="nav-item">
                <%= link_to "カート", public_cart_items_path, class: "nav-link text-dark" %>
              </li>

               <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-dark" %>
              </li>


             <% else %>

              <li class="nav-item">
                <%= link_to "About",  '/public/homes/about', class: "nav-link text-dark" %>
              </li>

               <li class="nav-item">
                <%= link_to "商品一覧", public_items_path, class: "nav-link text-dark" %>
              </li>

               <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: "nav-link text-dark" %>
              </li>

               <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-dark" %>
              </li>

              <% end %>

            </ul>
          </div>
        </div>
    </nav>
    </header>



    <main class ="mb-auto">
     <%= yield %>
     </main>
  </body>
</html>